name: Build Game Boy ROM

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip make wget

      - name: Download GBDK-2020
        run: |
          GBDK_VERSION=4.4.0
          wget -q https://github.com/gbdk-2020/gbdk-2020/releases/download/${GBDK_VERSION}/gbdk-linux64-${GBDK_VERSION}.tar.gz
          tar -xzf gbdk-linux64-${GBDK_VERSION}.tar.gz
          echo "GBDK_HOME=$PWD/gbdk" >> $GITHUB_ENV



      - name: Build ROM
        run: |
          make GBDK_HOME=${{ env.GBDK_HOME }}

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: pong-rom
          path: build/pong.gb
